---
- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  when: nginx_config == true 

- name: Create sites-available and sites-enabled directories as vanilla nginx doesnt have them
  file:
      path: "/etc/nginx/{{ item }}"
      state: directory
  with_items:
     - sites-available
     - sites-enabled
     - snippets

- name: Create nginx default fcgi config
  template:
    src: fastcgi.conf.j2
    dest: /etc/nginx/fastcgi.conf

- name: Create FPM config snippet
  template:
    src: fastcgi-php.conf.j2
    dest: /etc/nginx/snippets/fastcgi-php.conf

- name: Copy virtual host config
  template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob: "{{ playbook_dir }}/templates/nginx/*.j2"

- name: Delete default virtual host
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  when: nginx_delete_default_virtual_host == true

- name: Verify virtual host configs
  command: nginx -t
  when: nginx_verify_virtual_host_configs == true

- name: Find all virtual host configs
  find:
    paths: /etc/nginx/sites-available
  register: virtual_host_configs

- name: Symlink virtual hosts
  file:
    src: "{{ item.path }}"
    dest: /etc/nginx/sites-enabled/{{ item.path | basename }}
    state: link
  when: virtual_host_configs.matched > 0
  with_items: "{{ virtual_host_configs.files }}"
  notify: reload nginx
  
